# This is a basic workflow to help you get started with Actions
name: Deploy to AWS

# Controls when the action will run. Invokes the workflow on push events but only for the main branch
on:
  push:
    branches: [ main ]

env:
  
  AWS_REGION : us-east-2

# Permission can be added at job level or workflow level    
permissions:
      id-token: write   # This is required for requesting the JWT
      contents: read    # This is required for actions/checkout
jobs:
  TF-Plan:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: ${{ secrets.DEPLOYER_ASSUME_ROLE_ARN }}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ env.AWS_REGION }}
      # Hello from AWS: WhoAmI
      - name: TF Plan
        run: |
          cd ./platform/workloads
          terraform init -backend-config=./config.s3.tfbackend
          terraform workspace new nonprod || echo "Environment created"
          terraform workspace select nonprod
          terraform plan -var-file=./nonprod.tfvars -var provider_role_arn=${{ secrets.DEPLOYER_ASSUME_ROLE_ARN }}